name: Push Docker Image to ECR

on: 
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR 
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push Docker image
        run: |
          docker build -t 565512777831.dkr.ecr.us-east-1.amazonaws.com/web-image:latest .
          docker push 565512777831.dkr.ecr.us-east-1.amazonaws.com/web-image:latest

   

