name: add

on:
  push:
    branches:
      - main

jobs:
  Addition:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run add check
        run: python add.py
