name: Environment Creation Workflow

on:
  workflow_run:
    workflows: ["Create Production Environment"]
    types:
      - completed

jobs:
  create_production_environment:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.name == 'Create production Environment' && github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Production Environment
        run: |
          echo "Creating production environment"
         

