name: Leap Year

on:
  push:
    branches:
      - main

jobs:
  leap-year-check:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies

      - name: Run leap year check
        run: python leap_year.py
